/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TwCaller {
        "avatarSrc": string;
        "btnText": string;
        "callEndpoint": string;
        "calleName": string;
        "calleNumber": string;
        "hideCloseBtn": boolean;
    }
}
declare global {
    interface HTMLTwCallerElement extends Components.TwCaller, HTMLStencilElement {
    }
    var HTMLTwCallerElement: {
        prototype: HTMLTwCallerElement;
        new (): HTMLTwCallerElement;
    };
    interface HTMLElementTagNameMap {
        "tw-caller": HTMLTwCallerElement;
    }
}
declare namespace LocalJSX {
    interface TwCaller {
        "avatarSrc"?: string;
        "btnText"?: string;
        "callEndpoint"?: string;
        "calleName"?: string;
        "calleNumber"?: string;
        "hideCloseBtn"?: boolean;
        "onClosed"?: (event: CustomEvent<any>) => void;
        "onOpened"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "tw-caller": TwCaller;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tw-caller": LocalJSX.TwCaller & JSXBase.HTMLAttributes<HTMLTwCallerElement>;
        }
    }
}
