/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CallDialog {
        "callDuration": number;
        "isOpen": boolean;
        "logoSrc": string;
    }
    interface TwCaller {
        "avatarSrc": string;
        "btnText": string;
        "callEndpoint": string;
        "calleNumber": string;
    }
}
declare global {
    interface HTMLCallDialogElement extends Components.CallDialog, HTMLStencilElement {
    }
    var HTMLCallDialogElement: {
        prototype: HTMLCallDialogElement;
        new (): HTMLCallDialogElement;
    };
    interface HTMLTwCallerElement extends Components.TwCaller, HTMLStencilElement {
    }
    var HTMLTwCallerElement: {
        prototype: HTMLTwCallerElement;
        new (): HTMLTwCallerElement;
    };
    interface HTMLElementTagNameMap {
        "call-dialog": HTMLCallDialogElement;
        "tw-caller": HTMLTwCallerElement;
    }
}
declare namespace LocalJSX {
    interface CallDialog {
        "callDuration"?: number;
        "isOpen"?: boolean;
        "logoSrc"?: string;
        "onClose"?: (event: CustomEvent<any>) => void;
    }
    interface TwCaller {
        "avatarSrc"?: string;
        "btnText"?: string;
        "callEndpoint"?: string;
        "calleNumber"?: string;
        "onClosed"?: (event: CustomEvent<any>) => void;
        "onOpened"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "call-dialog": CallDialog;
        "tw-caller": TwCaller;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "call-dialog": LocalJSX.CallDialog & JSXBase.HTMLAttributes<HTMLCallDialogElement>;
            "tw-caller": LocalJSX.TwCaller & JSXBase.HTMLAttributes<HTMLTwCallerElement>;
        }
    }
}
